  export const videoData = [
    {
      id: "694f6b28-b847-4d36-94eb-ca13d943aad8",
      title: "Sticky Rice Matcha",
      category: "Drip and Culture",
      description: "Shot by Josiah Shaw\nEdited by Marcos Valenzuela",
      runtime: "01:51",
      thumbnail: "assets/thumbnails/stickyricematcha.png",
      orientation: "landscape",
    },
    {
      id: "a20cd07a-c384-49be-98c3-26e60f5b68f2",
      title: "Rose",
      category: "Mary Mary Gifts",
      description: "\"Discover Mary Ann Rose, owner of the iconic gift shop Mary Mary Gifts in the beating heart of Chicago. In this short documentary, Mary vividly recounts her journey as a professional singer, delving into her mesmerizing travels and unearthing her profound affection for community bonds, and unique treasures.\" -Mathilde Laporte\n\nDirected and shot by Mathilde Laporte \nProduced by Michael Coston-Dykes \nGaffing by Lilia Zamkin \nSound by Mia Neff Kadwell and Joshua LeBlanc \nEdited by Marcos Valenzuela",
      runtime: "03:26",
      thumbnail: "assets/thumbnails/rose.jpg",
      orientation: "landscape",
    },
    {
      id: "d336fce2-cadc-4791-9460-1d96079ba641",
      title: "Caballos de Fuerza",
      category: "Lux Chicago",
      description: "A look into the young organizers of a cultural event blending traditional performance, contemporary culture, and the living heritage of the Mexican American community of Chicago, IL.\n\nShot and Directed by Luis Chavez and Benny Densmore\nEdited by Marcos Valenzuela",
      runtime: "04:13",
      thumbnail: "assets/thumbnails/cdf.png",
      orientation: "landscape",
    },
    {
      id: "4ff18faf-1eec-4690-a943-58c7a38a2938",
      title: "Zarai",
      category: "Lux Chicago",
      description: "Zarai Reyes is the owner of 'Zarai Imports', a Mexican artisan shop born from love for traditional craft and culture. Through her story, discover the resilience, sacrifice, and pride that define's her life's work—that of uplifting Mexican craftspeople and supporting their families.\n\nDirected by Genesis Flores\nShot by Luis Chavez\nEdited by Marcos Valenzuela",
      runtime: "02:59",
      thumbnail: "assets/thumbnails/zarai.jpg",
      orientation: "landscape",
    },
    {
      id: "ffb1353d-2d8c-4aab-85e2-a519399e055b",
      title: "Hilo de Cahue",
      category: "Lux Chicago",
      description: "Alex—who goes by 'Hilo'—is the creative force behind 'Hilo de Cahue'. In this short documentary, he retraces his aesthetic inspirations to a small rancho, cowboys, and family ties, and shares plans to pave the way for the next generation of creatives.\n\nDirected by Genesis Zamudio\nShot by Luis Chavez\nEdited by Marcos Valenzuela",
      runtime: "04:17",
      thumbnail: "assets/thumbnails/hilo.png",
      orientation: "landscape",
    },
    {
      id: "6329f1fe-9c42-4d68-b244-e368c7d1464a",
      title: "Jazzy Flowers",
      category: "Lux Chicago",
      description: "Jazzy Flowers, a floral landmark in Chicago's West Loop neighborhood, share their passion and inspiration for this blooming small-business that keeps family at the heart of their shop.\n\nDirected by Noe Jurado\nShot by Luis Chavez\nProduction Assistants - Genesis Zamudio and Xhelia Alvarez\nEdited by Marcos Valenzuela",
      runtime: "01:01",
      thumbnail: "assets/thumbnails/jazzyflowers.jpg",
      orientation: "landscape",
    },
    {
      id: "a53b843d-f418-4189-825b-570162db00b6",
      title: "Lowrider",
      category: "Lux Chicago",
      description: "A promotional reel for a lowrider artist.",
      runtime: "00:30",
      thumbnail: "assets/thumbnails/lowrider.png",
      orientation: "portrait",
    },
    {
      id: "3c9e4865-94be-4050-be4e-70d0ba3176fa",
      title: "'Caballos de Fuerza' Reel",
      category: "Lux Chicago",
      description: "A promotional reel for the Caballos de Fuerza event.",
      runtime: "00:38",
      thumbnail: "assets/thumbnails/cdf-reel.png",
      orientation: "portrait",
    },
        {
      id: "e4758430-4a7d-4032-b8c1-55341100c0f1",
      title: "40th Birthday Performance Reel",
      category: "Vitality Band Chicago",
      description: "A promotional reel for a luxury event band.\n\nShot by Luis Chavez \n Edited by Marcos Valenzuela",
      runtime: "00:57",
      thumbnail: "assets/thumbnails/vitality.png",
      orientation: "landscape",
    },
    {
      id: "eb587f39-0163-467c-a4f9-d6d5dd764b1b",
      title: "Forging Artistry",
      category: "DePaul University",
      description: "Artist and filmmaker Lily McCauley draws influence from her industrialist-surrounding upbringing and reflects on the burden of art creation.\n\nDirected and shot by Audrey Weber\nInterviewed by Charlotte Vollmer\nSound Recorded by Ryan Petrucci\nEdited by Marcos Valenzuela\nFeaturing Lily McCauley",
      runtime: "04:13",
      thumbnail: "assets/thumbnails/forgingartistry.jpg",
      orientation: "landscape",
    }
  ];